// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9hsIo31rrbkUb2qWAPHzr9W10akVgp54',
    appId: '1:603935617677:web:13d6a0abe4a006c738a8c4',
    messagingSenderId: '603935617677',
    projectId: 'enzet-invoice',
    authDomain: 'enzet-invoice.firebaseapp.com',
    storageBucket: 'enzet-invoice.firebasestorage.app',
    measurementId: 'G-V6TQ6RGSRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXLveZtkzajs5vzbWoS05XlpIaw-sC6dk',
    appId: '1:603935617677:android:8ed894e6cd8d7ae838a8c4',
    messagingSenderId: '603935617677',
    projectId: 'enzet-invoice',
    storageBucket: 'enzet-invoice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyFiDZU9te6bKTP7kGwhusAAwhklPWGXc',
    appId: '1:603935617677:ios:7b6a30aa4a92e2c038a8c4',
    messagingSenderId: '603935617677',
    projectId: 'enzet-invoice',
    storageBucket: 'enzet-invoice.firebasestorage.app',
    iosBundleId: 'com.example.enzet',
  );
}
